// Native release-build gate. See docs/dev/csv-performance-gate.md.
import assert from 'node:assert/strict';
import { execFile } from 'node:child_process';
import { open, mkdir, stat, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { performance } from 'node:perf_hooks';
import { setTimeout as delay } from 'node:timers/promises';
import { startIsolatedToken, until } from './lib/token-automation.mjs';

const exec = promisify(execFile);
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const base = path.join(root, 'target/verification/csv-gate');
const bytes = 1024 ** 3; // 1 GiB, deliberately stricter than decimal 1 GB.
const limits = { openMs: 2000, navigationP95Ms: 100, sampledRssBytes: 3 * bytes };
const prefix = '42,"Bergen, Norway","a ""quote""","line one\nline two",æøå,123.45,';
const suffix = ',tail\n';
const record = Buffer.from(prefix + 'x'.repeat(512 - Buffer.byteLength(prefix + suffix)) + suffix);
assert.equal(record.length, 512);

async function fixture(file, size) {
  // Reuse only fixtures generated by this version, with the expected size.
  const manifest = `${file}.json`;
  const signature = { version: 1, size, record: record.toString('base64') };
  try {
    if ((await stat(file)).size === size &&
        JSON.stringify(JSON.parse(await readFile(manifest, 'utf8'))) === JSON.stringify(signature)) return;
  } catch { /* missing/incomplete fixture: regenerate */ }
  const handle = await open(file, 'w');
  const block = Buffer.from(record.toString().repeat(2048));
  try {
    let offset = 0;
    while (offset < size) {
      const { bytesWritten } = await handle.write(block, 0, Math.min(block.length, size - offset), offset);
      assert(bytesWritten > 0);
      offset += bytesWritten;
    }
  } finally { await handle.close(); }
  await writeFile(manifest, JSON.stringify(signature));
}

await mkdir(base, { recursive: true });
if (process.argv.includes('--check-fixture')) {
  const file = path.join(base, 'fixture-check.csv');
  await fixture(file, 4096);
  assert.deepEqual(await readFile(file), Buffer.from(record.toString().repeat(8)));
  console.log('Fixture generation checked: 4096 bytes, 8 complete records, quoted multiline/UTF-8 fields.');
  process.exit(0);
}
const binary = path.resolve(process.argv[2] ?? path.join(root, 'target/release/token'));
await stat(binary); // Do not generate 1 GiB if the binary is missing.
const file = path.join(base, 'multiline-1gib.csv');
await fixture(file, bytes);
// Explicit warm-cache attempt, bounded scratch memory. No fixture work is timed.
const handle = await open(file, 'r');
try {
  const block = Buffer.alloc(1024 ** 2);
  while ((await handle.read(block)).bytesRead) { /* sequential pre-read */ }
} finally { await handle.close(); }
const run = await startIsolatedToken({
  root, binary, name: 'csv-gate', files: { 'ready.txt': 'ready\n' }, openFiles: ['ready.txt'],
  configYaml: 'lsp:\n  enabled: false\nsession:\n  restore: false\n  save_on_exit: false\n',
});
const report = {
  schema: 1, binary, fixtureBytes: bytes, rows: bytes / 512, limits,
  platform: process.platform, arch: process.arch, cpu: os.cpus()[0]?.model,
  totalMemoryBytes: os.totalmem(), date: new Date().toISOString(),
  cache: 'sequential pre-read; OS residency not guaranteed',
  memoryMethod: 'process RSS sampled using ps every 100 ms; may miss short peaks',
  passed: false,
};
try { report.commit = (await exec('git', ['rev-parse', 'HEAD'], { cwd: root })).stdout.trim(); }
catch { report.commit = null; }
let sampling = true;
let peak = 0;
let memoryError;
const sampler = (async () => {
  while (sampling) {
    try {
      const rss = Number((await exec('ps', ['-o', 'rss=', '-p', String(run.child.pid)], { timeout: 1000 })).stdout.trim()) * 1024;
      if (!Number.isFinite(rss) || rss <= 0) throw new Error('RSS unavailable');
      peak = Math.max(peak, rss);
    } catch (error) { memoryError = error.message; }
    await delay(100);
  }
})();
try {
  await run.waitForStartup();
  const start = performance.now();
  await run.client.openPaths([{ path: file }]); // wait:true waits for CLOSE, not open.
  await until(async () => {
    const state = await run.client.state();
    return state.document_name === path.basename(file) && state.line_count === report.rows * 2 + 1;
  }, { label: 'full CSV text loaded (50 MiB rejection currently fails here)', timeoutMs: 15000, intervalMs: 20 });
  report.textLoadedMs = performance.now() - start;
  let state = await run.client.state();
  if (!state.csv) state = await run.client.action('CsvToggle');
  assert.equal(state.csv?.rows, report.rows, 'all CSV records parsed');
  assert.equal(state.csv?.columns, 8, 'quoted commas and multiline records preserved');
  // Completion arrives after a native rendered frame, not just command dispatch.
  await run.client.profileFrames(1);
  report.openMs = performance.now() - start;
  const navigation = [];
  for (let i = 0; i < 20; i++) {
    const began = performance.now();
    state = await run.client.action(i % 2 === 0 ? 'CsvLastCell' : 'CsvFirstCell');
    assert.equal(state.csv.selected_row, i % 2 === 0 ? report.rows - 1 : 0);
    assert.equal(state.csv.selected_value, i % 2 === 0 ? 'tail' : '42');
    await run.client.profileFrames(1);
    navigation.push(performance.now() - began);
  }
  navigation.sort((a, b) => a - b);
  report.navigationP95Ms = navigation[Math.ceil(navigation.length * 0.95) - 1];
  assert(report.openMs <= limits.openMs, `open took ${report.openMs.toFixed(0)} ms`);
  assert(report.navigationP95Ms <= limits.navigationP95Ms, 'navigation exceeded target');
  report.passed = true;
} catch (error) {
  report.error = error.stack;
} finally {
  sampling = false;
  await sampler;
  report.sampledPeakRssBytes = peak;
  if (memoryError || !peak || peak > limits.sampledRssBytes) {
    report.passed = false;
    report.memoryError = memoryError ?? `RSS ${peak} outside gate`;
  }
  try { await run.stop(); } catch (error) { report.passed = false; report.shutdownError = error.message; }
  report.stderr = run.stderr;
  const output = path.join(run.fixture, 'report.json');
  await writeFile(output, JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report, null, 2));
  console.log(`Report: ${output}`);
  process.exitCode = report.passed ? 0 : 1;
}
