//! Preferences navigation and placement. Labels never select application behavior.
use super::catalog::Setting;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub(crate) struct GroupId(pub &'static str);

#[derive(Debug)]
pub(crate) struct Group {
    pub id: GroupId,
    pub title: &'static str,
    pub settings: &'static [Setting],
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PageKind {
    Preferences,
    Formatters,
    LanguageServers,
    AiProviders,
    Keymap,
}

#[derive(Debug)]
pub(crate) struct Page {
    key: &'static str,
    label: &'static str,
    pub kind: PageKind,
    pub groups: &'static [Group],
}

macro_rules! pages {
    ($($id:ident => $page:expr),+ $(,)?) => {
        /// Stable navigation identity, independent of labels and display order.
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub enum CategoryId { $($id),+ }

        pub fn categories() -> &'static [CategoryId] {
            &[$(CategoryId::$id),+]
        }

        impl CategoryId {
            pub(crate) fn page(self) -> &'static Page {
                match self { $(Self::$id => &$page),+ }
            }
        }
    };
}

impl CategoryId {
    pub fn label(self) -> &'static str {
        self.page().label
    }

    pub fn index(self) -> usize {
        // Both the enum and the navigation list are generated by pages!.
        categories()
            .iter()
            .position(|id| *id == self)
            .expect("every category is declared in pages!")
    }

    /// Accept stable keys as well as display names for screenshot scenarios.
    pub fn from_name(name: &str) -> Option<Self> {
        categories().iter().copied().find(|id| {
            id.page().key.eq_ignore_ascii_case(name) || id.label().eq_ignore_ascii_case(name)
        })
    }
}

pages! {
    All => Page { key: "all", label: "All Settings", kind: PageKind::Preferences, groups: &[] },
    Appearance => Page {
        key: "appearance", label: "Appearance", kind: PageKind::Preferences,
        groups: &[
            Group { id: GroupId("appearance.theme"), title: "Theme", settings: &[Setting::Theme] },
            Group { id: GroupId("appearance.chrome"), title: "Editor chrome", settings: &[Setting::Scrollbar, Setting::IndentGuides, Setting::Blink] },
            Group { id: GroupId("appearance.status"), title: "Status bar", settings: &[Setting::StatusFont] },
        ],
    },
    Editor => Page {
        key: "editor", label: "Editor", kind: PageKind::Preferences,
        groups: &[
            Group { id: GroupId("editor.assistance"), title: "Editing assistance", settings: &[Setting::Surround, Setting::Brackets, Setting::Hover, Setting::HoverDelay, Setting::InlayHints] },
            Group { id: GroupId("editor.indentation"), title: "Indentation", settings: &[Setting::EditorConfig, Setting::IndentStyle, Setting::IndentSize, Setting::TabWidth] },
        ],
    },
    FilesSession => Page {
        key: "files-session", label: "Files & Session", kind: PageKind::Preferences,
        groups: &[
            Group { id: GroupId("files.format"), title: "File format", settings: &[Setting::LineEnding] },
            Group { id: GroupId("files.explorer"), title: "File Explorer", settings: &[Setting::ExplorerAutoReveal] },
            Group { id: GroupId("files.saving"), title: "Saving", settings: &[Setting::AutoSave, Setting::AutoSaveDelay, Setting::AutoReload] },
            Group { id: GroupId("files.session"), title: "Session", settings: &[Setting::SessionRestore, Setting::SessionSave] },
        ],
    },
    Formatting => Page {
        key: "formatting", label: "Formatting", kind: PageKind::Formatters,
        groups: &[Group { id: GroupId("formatting.saving"), title: "Save behavior", settings: &[Setting::FormatOnSave, Setting::AutoSaveFormatting] }],
    },
    Completion => Page {
        key: "completion", label: "Completion", kind: PageKind::Preferences,
        groups: &[
            Group { id: GroupId("completion.general"), title: "General", settings: &[Setting::CompletionEnabled, Setting::CompletionMenu] },
            Group { id: GroupId("completion.local"), title: "Local suggestions", settings: &[Setting::CompletionWords, Setting::CompletionMinLength] },
            Group { id: GroupId("completion.inline"), title: "Inline suggestions", settings: &[Setting::InlineEnabled, Setting::InlineDelay, Setting::InlineSuffix] },
            Group { id: GroupId("completion.privacy"), title: "Privacy", settings: &[Setting::InlineStatistics] },
        ],
    },
    LanguageServers => Page { key: "LSP", label: "Language servers", kind: PageKind::LanguageServers, groups: &[] },
    AiProviders => Page { key: "AI", label: "AI Providers", kind: PageKind::AiProviders, groups: &[] },
    Keymap => Page { key: "keymap", label: "Keymap", kind: PageKind::Keymap, groups: &[] },
}

pub(crate) fn placement(setting: Setting) -> Option<(CategoryId, &'static Group)> {
    categories().iter().find_map(|&category| {
        category
            .page()
            .groups
            .iter()
            .find(|group| group.settings.contains(&setting))
            .map(|group| (category, group))
    })
}

/// Ordinary rows used both by the preferences list and by specialized pages.
pub(crate) fn preference_rows(category: CategoryId) -> impl Iterator<Item = super::SettingRow> {
    category.page().groups.iter().flat_map(|group| {
        group.settings.iter().map(|&setting| super::SettingRow {
            kind: super::RowKind::Preset(setting),
            section: group.title,
            name: setting.descriptor().name.into(),
            description: setting.descriptor().description.into(),
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn settings_catalog_has_unique_keys_and_exactly_one_primary_placement() {
        let mut keys = HashSet::new();
        let mut groups = HashSet::new();
        let mut settings = HashSet::new();
        let mut categories_seen = HashSet::new();
        for &category in categories() {
            assert!(categories_seen.insert(category.page().key));
            assert_eq!(CategoryId::from_name(category.label()), Some(category));
            assert_eq!(categories()[category.index()], category);
            for group in category.page().groups {
                assert!(groups.insert(group.id), "duplicate group {:?}", group.id);
                assert!(!group.settings.is_empty());
                for &setting in group.settings {
                    assert!(settings.insert(setting), "duplicate placement: {setting:?}");
                    assert!(
                        keys.insert(setting.descriptor().key),
                        "duplicate key: {setting:?}"
                    );
                }
            }
        }
        assert_eq!(settings, Setting::ALL.iter().copied().collect());
    }
}
